Add possibility to provide path as argument and default value
elabit/robotmk pull request #374
Opened 2023-10-11 10:33 UTC by racicLuka

Added possibility to call the script with an argument:
`./robotmk_collector.ps1 "path_as_argument"`

Also, if `env:MK_CONFDIR` is not present, the path will default to `C:\ProgramData\checkmk\agent\config\robotmk.json`

2023-10-11 10:55 UTC, jherbel requested changes
Let's also remove the comments, they shouldn't be necessary

2023-10-11 10:55 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +    #If the path is provided as an argument, use it.
Let's move the new code into a separate function

2023-10-11 10:55 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +        [parameter(Mandatory=$false, Position=0)]
Since we are never calling `Main` with a parameter, we can remove it alltogether

2023-10-11 10:55 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +        $ConfigPath = $env:MK_CONFDIR
```
$configDir = $env:MK_CONFDIR
if (!$configDir) {
    $configDir = 'C:\ProgramData\checkmk\agent\config'
}
return $configDir + '\robotmk.json'
```

2023-10-11 12:30 UTC, jherbel requested changes
Please remove the code comments and squash the PR into a single commit

2023-10-11 12:30 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +        [array]$ProvidedPath
I think this should be `String []`

2023-10-11 12:30 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +    param (
```
Param (
        [parameter(Mandatory=$true, Position=0)]
```

2023-10-11 12:30 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +        [array]$ProvidedPath
Let's call it `$CommandLineArgs` or so, since we don't know yet if there actually is a path

2023-10-11 12:30 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +Main $args
This is not needed

2023-10-11 14:17 UTC, racicLuka commented
I can squash and merge once you approve the PR, if that is OK with you?

2023-10-11 15:09 UTC, jherbel commented
> I can squash and merge once you approve the PR, if that is OK with you?

Depends on how the commit would look afterwards. The easiest way would be to simply squash locally and do a force push.

2023-10-12 09:35 UTC, jherbel commented on checkmk_extensions/agent/robotmk_collector.ps1
> +        [array]$ProvidedPath
What I meant:
`[String []]$CommandLineArgs`
So an array of strings

2023-10-12 09:36 UTC, jherbel reviewed
See the last remaining comment about `[String []]$CommandLineArgs`

2023-10-12 11:52 UTC, racicLuka commented on checkmk_extensions/agent/robotmk_collector.ps1
> +    if ($CommandLineArgs -ne "" -and $CommandLineArgs.Count -gt 0) {
I needed to change this to `$CommandLineArgs -ne ""` because now, if there are no arguments provided, it considers it as an empty string.

2023-10-12 12:07 UTC, jherbel approved these changes

2023-10-12 12:22 UTC, merged