Dev/sol/tokio
elabit/robotmk pull request #433
Opened 2023-11-09 09:18 UTC by SoloJacobs

WIP

2023-11-10 08:55 UTC, jherbel approved these changes
Very nice, thanks!

2023-11-10 16:35 UTC, jherbel requested changes
After trying this out and then debugging for a long time, I found out that we cannot use `std::hint::spin_loop` in combination with `tokio`. I cannot say what the underlying problem is. Using the two in combination leads to random deadlocks. Replacing `std::hint::spin_loop` with `tokio::task::yield_now().await` works.

2023-11-13 07:15 UTC, SoloJacobs commented
> After trying this out and then debugging for a long time, I found out that we cannot use `std::hint::spin_loop` in combination with `tokio`. I cannot say what the underlying problem is. Using the two in combination leads to random deadlocks. Replacing `std::hint::spin_loop` with `tokio::task::yield_now().await` works.

The explanation is probably this: As soon as the scheduler enters the loop, there is no way for it to exit it. Since the scheduler here is the tokio scheduler, it will only pause a task, if the task itself reports, that it can be paused. Pausing here here just means awaiting a future. In your implementation this works correctly, since now the scheduler gets the chance to resume other tasks.

I am not sure what you changed, maybe we should have a look together at this change, and what other ideas I have here.

2023-11-13 08:20 UTC, jherbel approved these changes

2023-11-13 08:34 UTC, merged