Allow unzipping during setup
elabit/robotmk pull request #540
Opened 2024-05-23 12:24 UTC by SoloJacobs

CMK-17430

I guess it will take me a bit longer to get the permissions for the unzipped directories working. Can you maybe have a look at this draft, which only works for non-headed execution.

2024-05-23 12:29 UTC, SoloJacobs commented
Some similiar ideas:
* The checkmk bakery also transfers packages (it uses an .msi instead). So, we could also build this functionality into the Checkmk server.
*` rcc robot wrap` is essentially the same as here, but sets some files to executable.

2024-05-23 12:57 UTC, jherbel commented
This looks quite promising already. There main point currently unclear to me is how to best handle the various paths. The bakery plugin currently builds eg. the path to the robot file from the base directory and the relative path specified by the user. However, the directory the scheduler unzips into is probably a different directory. So we could of course adjust the bakery plugin, but then we would have a bit of duplicated business logic, namely how to construct the path to the robot file for managed robots (basically `managed_dir/plan_id/...`). Maybe this is perfectly fine, but I think we should briefly discuss this. Ping me please.

2024-05-27 07:37 UTC, jherbel requested changes
Only one small comment, looks good otherwise :+1:

2024-05-27 07:37 UTC, jherbel commented on .github/workflows/system_tests.yaml
> +      - run: dir data
Can be removed

2024-05-27 13:40 UTC, jherbel approved these changes

2024-05-28 06:11 UTC, merged