Scheduler main: Check for cancellation between base setup and setup steps
elabit/robotmk pull request #651
Opened 2024-11-22 09:34 UTC by jherbel

Barely makes a difference but is the correct thing to do.

2024-11-26 13:25 UTC, SoloJacobs requested changes

2024-11-26 13:25 UTC, SoloJacobs commented on src/bin/scheduler/main.rs
> +    if global_config.cancellation_token.is_cancelled() {
Changing status to request changes requires me to leave a comment...

2024-11-26 14:14 UTC, jherbel commented on src/bin/scheduler/main.rs
> +    if global_config.cancellation_token.is_cancelled() {
Done

2024-11-27 08:43 UTC, SoloJacobs approved these changes

2024-11-27 08:49 UTC, merged